### ISSUE TITLE
bb-lp-cli looking for missing base.css file

### ISSUE THREAD

**Issue by santam85** [Backbase/bb-lp-cli#17]
On Ubuntu x64 v16.04, with node v4.4.2, bb-lp-cli fails to build widgets, looking for a ./styles/base.css file
Tested on an untouched lp-widget generated with 'bb generate'

**Comment by dragosh** [comment]
Hi @santam85 can you reproduce this issue with `bblp generate` instead?

**Comment by santam85** [comment]
Just tried on the same system. Reproduction steps are:
1. Install clean Ubuntu x64 v16.04
2. Use nvm to install and use node v4.4.2
3. Install bb-lp-cli 1.9.11
4. bblp generate
5. bblp build

If I add an empty base.css file in styles folder, the build is successful and functions properly.
